In [22]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.datasets import load_digits
import matplotlib.pyplot as plt
digits = load_digits()

In [23]:
from sklearn.model_selection import train_test_split
X_train, y_train, X_test, y_test = train_test_split(digits.data, digits.target, test_size=0.3)

In [25]:
svm =SVC(gamma='auto')
svm.fit(X_train, y_train)
svm.score(X_test, y_test)

ValueError: bad input shape (540, 64)

In [26]:
rf = RandomForestClassifier(n_estimators=40)

In [27]:
rf.fit(X_train, y_train)
rf.score(X_test, y_test)

ValueError: Number of labels=540 does not match number of samples=1257

In [20]:
def get_score(modle, X_train, y_train, X_test, y_test ):
    modle.fit(X_train,y_train)
    return modle.score(X_test,y_test)
    
get_score(LogisticRegression(),X_train,X_test, y_train,y_test)

ValueError: bad input shape (599, 64)

In [21]:
get_score(RandomForestClassifier(), X_train,X_test,y_train,y_test)

ValueError: Number of labels=599 does not match number of samples=1198

In [18]:
get_score(SVC(),X_train,X_test,y_train,y_test)

ValueError: bad input shape (599, 64)

In [9]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [10]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print (test_index,train_index)

[0 1 2] [3 4 5 6 7 8]
[3 4 5] [0 1 2 6 7 8]
[6 7 8] [0 1 2 3 4 5]


In [12]:
from sklearn.model_selection import StratifiedKFold 
folds =StratifiedKFold(n_splits=3)

scores_logistic=[]
scores_svm=[]
scores_rf=[]

for train_index, test_index in folds.split(digits.data, digits.target):
    X_train, X_test, y_train, y_test = digits.data[train_index], digits.data[test_index], \
                                       digits.target[train_index], digits.target[test_index]
    get_score(LogisticRegression(),X_train,X_test,y_train,y_test)
    get_score(SVC(), X_train, X_test, y_train, y_test)
    get_score(RandomForestClassifier(n_estimators=40), X_train, X_test, y_train, y_test)


ValueError: bad input shape (599, 64)